### ISSUE TITLE
Command timeout when server name, player name contain special characters.

### ISSUE THREAD

**Issue by tianyu-00** [calico-crusade/palworld-rcon-sharp#2]
The "Showplayers" command times out when the server has players with names containing special characters.
Same happens with "Info" when server name contains special characters.

EXCEPTIONS in order:
Exception thrown: 'System.TimeoutException' in System.Private.CoreLib.dll
The thread 0xb5c has exited with code 0 (0x0).
Exception thrown: 'System.TimeoutException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.ObjectDisposedException' in System.Private.CoreLib.dll
The program '[54328] PalWorld.Rcon.Cli.exe' has exited with code 0 (0x0).

Catched Exception:
Sorry! Something went wrong: Error sending packet >> System.TimeoutException: The operation has timed out.
   at PalWorld.Networking.Extensions.WaitTimeout[T](Task`1 task, Int32 timeoutMs)
   at PalWorld.Networking.RconClient.Send(RconPacket packet)
   at PalWorld.Networking.PersistentRconClient.InternalWrite(RconPacket packet, Int32 tryCount)
The operation has timed out.

**Comment by calico-crusade** [comment]
This is a known issue with Pal World's RCON implementation. Technically the base RCON protocol does not support anything other than ASCII characters. To support Non-ASCII characters, the server is supposed to base-64 encode the data that has an invalid character in it. 

There isn't anything I can do client side to fix this as it seems like the server just does not respond to the RCON request if a player has a special character (hence the timeout). I will do some more testing when I have a moment, but for right now, there isn't much I can do.

[RCON protocol structure](https://developer.valvesoftware.com/wiki/Source_RCON_Protocol#Basic_Packet_Structure)

**Comment by tianyu-00** [comment]
Hmm i see, appreciate the info.

**Comment by calico-crusade** [comment]
One potential solution you could try (though I'm not optimistic that it would work) is changing the encoding the library uses for packet parsing.

This can be done by providing the `encoding` overload:
```csharp
var persistent = new PersistentRconClient(host, port, pass, encoding: Encoding.UTF32);
var normal = new RconClient(host, port, user, encoding: Encoding.ASCII);
```

**Comment by tianyu-00** [comment]
yh ive tried adding the encoder overload before and it didnt seem to work hhh. Guess at the moment ill just add try and catches to handle any timeout exceptions😁. btw really appreciate the work done, keep it up👍.

**Comment by Balphagorevr** [comment]
I wanted to add that if a server owner implements Palguard, they can activate Base64 Rcon. If we can verify having an Encoder parameter that can work with Base64?

(Taken from the developer's Discord showing config options for Palguard)
![image](https://github.com/calico-crusade/palworld-rcon-sharp/assets/28694575/7abc2e0f-d3d0-47b6-b782-e26413b6d59f)

**Comment by Balphagorevr** [comment]
Check out my pull request/repo which implements a workaround for this by using Palguard's base64 encoding/decoding by overriding RCON input/output to Base64 to support these characters.

Pull Request https://github.com/calico-crusade/palworld-rcon-sharp/pull/3
